version: "3"
services:
  node:
    build: ./
    container_name: node-for-react
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 3000:3000
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
