# Generated by Django 3.2.7 on 2021-11-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='roommember',
            old_name='user_id',
            new_name='user',
        ),
    ]
