# Generated by Django 3.2.7 on 2021-11-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211115_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommessage',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='roommessage',
            old_name='send_by',
            new_name='send_user',
        ),
    ]
